// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
"time"
)

type Category struct {
	ID           uint   `gorm:"primaryKey"`
	CategoryName string `gorm:"column:category_name"`
	Description  string `gorm:"column:description"`
	CreatedAt time.Time `gorm:"column:created_at"`
    UpdatedAt time.Time `gorm:"column:updated_at"`
}

type CategoryJson struct {
	ID           uint      `bson:"_id,omitempty"`
	CategoryName string    `bson:"category_name,omitempty"`
	Description  string    `bson:"description,omitempty"`
	CreatedAt    time.Time `bson:"created_at,omitempty"`
	UpdatedAt    time.Time `bson:"updated_at,omitempty"`
}

type NewCategory struct {
	CategoryName string `json:"category_name"`
	Description  string `json:"description"`
}

